const fs=require("fs");
const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,AlignmentType,
HeadingLevel,BorderStyle,WidthType,ShadingType,ImageRun,PageNumber,Footer}=require("docx");
const GREEN="1A3D28",GREY="555555";
const CW=9360;
const bd={style:BorderStyle.SINGLE,size:1,color:"BBBBBB"}; const bds={top:bd,bottom:bd,left:bd,right:bd};
const H=(t,l)=>new Paragraph({heading:l,keepNext:true,children:[new TextRun(t)]});
const P=(t,o={})=>new Paragraph({spacing:{after:130,line:288},alignment:AlignmentType.JUSTIFIED,...o,
  children:(Array.isArray(t)?t:[new TextRun({text:t,size:22})])});
function cell(t,w,head,keep){return new TableCell({borders:bds,width:{size:w,type:WidthType.DXA},
  shading:{fill:head?GREEN:"FFFFFF",type:ShadingType.CLEAR},margins:{top:50,bottom:50,left:90,right:90},
  children:[new Paragraph({alignment:head?AlignmentType.CENTER:AlignmentType.LEFT,keepNext:keep,
    children:[new TextRun({text:t,bold:head,color:head?"FFFFFF":"000000",size:18})]})]});}
function tbl(rows,widths){const last=rows.length-1;return new Table({width:{size:CW,type:WidthType.DXA},columnWidths:widths,
  rows:rows.map((r,ri)=>new TableRow({cantSplit:true,children:r.map((c,ci)=>cell(c,widths[ci],ri===0,ri<last))}))});}
// tcap: caption ABOVE a table (stays attached to it). caption: BELOW a figure.
function tcap(t){return new Paragraph({spacing:{before:160,after:60},keepNext:true,children:[new TextRun({text:t,size:18,italics:true,color:GREY})]});}
function caption(t){return new Paragraph({spacing:{before:60,after:160},children:[new TextRun({text:t,size:18,italics:true,color:GREY})]});}
function fig(path,w,h,cap){return [new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:120,after:40},keepNext:true,
  children:[new ImageRun({type:"png",data:fs.readFileSync(path),transformation:{width:w,height:h},altText:{title:cap,description:cap,name:cap}})]}),caption(cap)];}

const k=[];
// Title block
k.push(new Paragraph({spacing:{after:60},children:[new TextRun({text:"Using LiDAR to quantify, map, and conserve late-successional and old-growth forest in Maine, USA: Comment",bold:true,size:30,color:GREEN})]}));
k.push(new Paragraph({spacing:{after:40},children:[new TextRun({text:"Aaron R. Weiskittel",size:22,bold:true})]}));
k.push(new Paragraph({spacing:{after:60},children:[new TextRun({text:"University of Maine, Center for Research on Sustainable Forests, Orono, ME 04469, USA. aaron.weiskittel@maine.edu",size:18,color:GREY})]}));
k.push(new Paragraph({spacing:{after:120},children:[new TextRun({text:"Comment on Hagan, J.M., B. Shamgochian, M.M.L. Taylor & J.M. Reed. 2026. Ecosphere 17:e70670.",size:18,italics:true,color:GREY})]}));
k.push(new Paragraph({spacing:{after:240},children:[new TextRun({text:"Positionality: the author conducts forest inventory and biometric modeling in Maine and has a professional interest in how forest-inventory information is used in state policy. The analyses here use the original authors' archived data and public FIA and remote-sensing data, and all code is openly archived.",size:18,italics:true,color:GREY})]}));

k.push(H("1.  Introduction",HeadingLevel.HEADING_1));
k.push(P("All maps and models are wrong; the only useful question is whether they are useful for the decision at hand (Box 1976). This is not a special weakness of forest mapping, and we raise it in that constructive spirit. It is simply more acute for late-successional and old-growth (LSOG) forest, because LSOG is a continuous, multi-dimensional, and partly subjective condition that any classification must force into discrete classes (Gray et al. 2023). The map of Hagan et al. (2026) is a useful and timely product, and the useful question for it is the same as for any map: is it fit for the decision now being made with it, the prioritization of roughly $200-300 million in conservation funding under Maine's LD 1529 (Thompson et al. 2026)? Fitness at those stakes depends on properties the original analysis did not report: the map's agreement with independent maps and with unbiased ground inventory, and a confidence interval on the quantities taken from it. We provide both, using the authors' own archived data and public inventory over the same area, in the hope of strengthening, not diminishing, the use of LiDAR for this purpose."));
k.push(P("Hagan et al. (2026) provide a valuable, transparent, and timely contribution: a field-trained, wall-to-wall classification of LSOG forest across approximately 4.2 million hectares of Maine's unorganized townships, derived from publicly available airborne LiDAR. The authors archived their training data and code, the field effort is substantial, and the resulting map has focused overdue attention on older forest in a working landscape. We reproduced their random forest classifier exactly from the archived data, obtaining an out-of-bag accuracy of 94.2% for the Not-LSOG versus LSOG distinction against their reported 94.1%, with the same most-important predictor (canopy cover above 15 m). Nothing in this Comment questions the competence or the openness of the original analysis, both of which we commend. The authors are also candid about the limits of the work: they include a Limitations section, report that the model classifies true old growth correctly only 29.4% of the time, state that they could not estimate ingrowth, emphasize that old-forest definitions vary widely and materially change the result, and recommend ground-truthing before any management or conservation decision. Our aim is not to dispute these caveats but to quantify them, because the map is now being used quantitatively, for parcel-level prioritization and cost estimation, at a scale to which its stated uncertainties were never propagated."));
k.push(P("The difficulty of defining and inventorying older forest is long recognized and has been called a wicked problem (Spies 2004; Gray et al. 2023). National FIA-based assessments place old growth at about 6.3% of US forest (Barnett et al. 2023) and quantify it on federal lands (Pelz et al. 2023), and spaceborne GEDI lidar has been used to characterize old-growth structure elsewhere (Spracklen and Spracklen 2021). The original authors engage much of this literature, citing the national FIA assessments, the wicked-problem synthesis, and GEDI-based structural work; what the analysis does not do is use any independent product as a benchmark, place a sampling interval on its quantities, or ground the Maine estimate in the design-based inventory. Against that backdrop, our concern is narrow and methodological: when a single airborne map underwrites parcel-level acquisition and emerging carbon and conservation markets, its fitness depends on its agreement with independent maps and with unbiased ground inventory, on the uncertainty of every quantity derived from it, and on the validity of the trend used to motivate action. We assess each in turn."));
k.push(P("We make four points. First, training accuracy is high for every candidate approach and is therefore not the issue (Section 2). Second, independent operationalizations of LSOG, each with high training accuracy, disagree markedly at the landscape scale, which is the scale at which hectares are prioritized (Section 3). Third, the canopy-structure signal the method relies on is sensitive to large trees and tall canopy but largely insensitive to the dead-wood component that distinguishes old growth, so it maps tall, big-tree forest, which is roughly three times more extensive than ground-defined old forest (Section 4). Fourth, ground-based FIA inventory, the gold standard the LiDAR map approximates, places the amount of older forest with a sampling-error confidence interval the original analysis did not report, and shows the stock to be stable or increasing rather than rapidly declining (Section 5). Section 6 discusses implications."));

k.push(H("2.  Training accuracy is high for every approach, and is not the issue",HeadingLevel.HEADING_1));
k.push(P("The 463 archived training plots carry both the eight LiDAR canopy metrics and a parallel set of ground structural measurements (live and dead basal area, basal area and number of trees >= 40 cm dbh, quadratic mean diameter, coarse woody debris, and diameter variability). Using these, we estimated cross-validated AUC (repeated stratified five-fold cross-validation, 40 repeats; intervals from the repeat distribution) for three predictor sets against three binary targets (Table 1). Hagan's eight LiDAR metrics discriminate the field classes very well in-sample: AUC 0.990 for any-LSOG, 0.988 for LS+OG, and 0.966 for old growth. A canopy-height-only set and a ground-structure set also perform well for the broad classes. The training data are separable and the published classifier is internally sound; we emphasize this because it is the premise that makes the rest of the argument matter. Two features of Table 1 are nonetheless relevant. For old growth specifically, a canopy-height-only model, which approximates the information a spaceborne canopy-height product carries, is the weakest of the three (AUC 0.910), while ground structure is the strongest. And the full LiDAR model's high ranking ability coexists with the operating-point performance the authors report: in their own out-of-bag confusion matrix, only 29.4% of true old-growth plots were classified as old growth. High AUC and low operating accuracy are reconcilable under class imbalance and overlap, but for a map used to select specific hectares, it is operating performance on the rare, high-value class that governs the decision. Discrimination on labelled plots is a necessary property of any usable classifier; because it is achieved here by all three predictor sets, it cannot by itself distinguish among the very different maps those predictors produce when applied across the landscape (Section 3). The pattern is robust to classifier choice: under logistic regression the same ordering holds, with canopy height alone weakest for old growth (AUC 0.91) and ground structure strongest (0.97) (Appendix S1). Because the training plots are spatially dispersed but not independent, these cross-validated intervals are best read as lower bounds on uncertainty."));
k.push(tcap("Table 1. Cross-validated AUC (mean [95% interval]) recovering the field-assigned class from three predictor sets, on the 463 archived training plots."));
k.push(tbl([
 ["Target (prevalence)","Hagan 8 LiDAR","Canopy height only","Ground structure"],
 ["any-LSOG (0.39)","0.990 [0.988, 0.992]","0.984 [0.981, 0.987]","0.966 [0.962, 0.969]"],
 ["LS + OG (0.21)","0.988 [0.984, 0.990]","0.977 [0.973, 0.982]","0.970 [0.967, 0.973]"],
 ["old growth (0.04)","0.966 [0.954, 0.977]","0.910 [0.868, 0.933]","0.974 [0.966, 0.981]"],
],[2760,2200,2200,2200]));

k.push(H("3.  High training accuracy does not produce map agreement",HeadingLevel.HEADING_1));
k.push(P("The decisive test for policy use is not how well a model separates its own training plots but whether independent, equally defensible operationalizations of LSOG agree on the landscape. We compared three wall-to-wall classifications over the same area on a common 100 m grid: the reproduced Hagan LiDAR classifier; an FIA-field-structure class predicted from Potapov (GEDI-calibrated) canopy height; and the USFS TreeMap imputation of FIA structural class. They disagree substantially. Any-LSOG covers 21.9% of the area under our reproduction of the Hagan classifier, close to the 19.7% the authors report in their Table 7 (the small difference reflects grid resolution and analysis extent), against 14.0% under the canopy-height model and 7.8% under TreeMap, a 2.5- to 2.8-fold range. Spatially, the Hagan and canopy-height maps overlap on only about 21% of the hectares either one flags (Cohen's kappa 0.21); across all three methods, only 21% of the flagged footprint is agreed by all three, and more than half is flagged by a single method (Table 2; Fig. 1). Part of any pixel-level disagreement reflects geolocation and co-registration error among the products rather than true classification difference: spaceborne GEDI footprints alone carry a systematic geolocation error on the order of 10 m (Shannon et al. 2024), and airborne LiDAR and NAIP-derived products are not free of positional error either. This is one reason we emphasize the disagreement in total amount, which is insensitive to position; aggregate the comparison to 8-km hexagons, where such error averages out (Appendix S1); and treat the design-based FIA estimate, which carries no map geolocation error at all, as the reference (Section 5). Because we reproduced the published model exactly and a 20-seed ensemble bounds the reproduced area at 4.23% (SD 0.06), the disagreement among methods is genuine rather than an artifact of our reproduction. We stress that none of these products is ground truth, including the two we constructed; the canopy-height map (built on a noisier, GEDI-calibrated product) and the TreeMap imputation are themselves proxies, and TreeMap imputation smooths rare classes, so its area (computed at native 30 m resolution) is best read as a lower bound and its pixel-level agreement is weak. The point is not that any one map is correct but that credible operationalizations of the same target disagree by this much, which is the property a single-map prioritization must reckon with."));
k.push(P("The consequence for prioritization is direct. If a program protects the highest-priority hectares, the overlap of the protected sets selected by the Hagan map versus the canopy-height map is only 0.16 to 0.30 (Jaccard) for the top 5% to 20% of hectares; that is, 70% to 84% of the prioritized ground differs depending on which equally defensible map is used (Fig. 1). A US $200-300 million acquisition program steered by one map would purchase substantially different forest than the same program steered by another. Each map can have excellent training accuracy and the maps can still disagree on most of the ground, because the disagreement lives in the definitional and methodological choices rather than in the fit to any one training set."));
k.push(P("These figures are for the broad any-LSOG class, which includes the original transitioning category. The picture at the strict old-growth level is different and instructive. The reproduced LS+OGL class covers about 4% of the area, and the unbiased FIA design-based estimate of older forest (Section 5) is 3.9% [3.3, 4.6], so the methods agree closely on the rare, well-defined old-growth core. The disagreement is concentrated in the broad, transitioning envelope, which is also the part that most enlarges the conservation target and its cost. Comparing across these definitions requires care, because the original LSOG class, FIA old forest by stand age, and old growth are related but not identical targets; the design-based FIA estimate is the unbiased anchor for the strict class. The authors themselves emphasize that definitions vary and materially change the result, citing a landscape where relaxing the old-growth definition moved the estimate from 2.7% to 15%; the cross-method spread we document is that same sensitivity expressed spatially."));
k.push(tcap("Table 2. Wall-to-wall any-LSOG area and pairwise agreement across three independent maps over the study area. The Hagan any-LSOG area is our reproduction (21.9%); the authors report 19.7% in their Table 7."));
k.push(tbl([
 ["Method","any-LSOG (% area)","kappa vs Hagan","Jaccard vs Hagan"],
 ["Hagan (airborne LiDAR canopy)","21.9","n/a","n/a"],
 ["v5.1-GEDI (FIA class on canopy height)","14.0","0.21","0.21"],
 ["TreeMap (FIA structural imputation)","7.8","0.01","0.03"],
 ["3-way: % of flagged area agreed by all three","21.0","",""],
],[3960,1800,1800,1800]));
k.push(...fig("figs/Fig1_crossmap.png",384,508,"Fig. 1. Cross-map disagreement. (a) any-LSOG area by method (2.8-fold range); (b) the same 24-km window classified by each method; (c) only 21% of the flagged footprint is agreed by all three; (d) overlap of the top-priority protected hectares between maps (Jaccard 0.16-0.30)."));

k.push(H("4.  The canopy signal captures big trees better than old-growth structure",HeadingLevel.HEADING_1));
k.push(P("Old growth is defined ecologically by large old trees, structural complexity, and abundant dead wood. Using the archived plots, we asked how well the eight LiDAR canopy metrics predict these defining attributes (cross-validated R-squared). They predict large-tree basal area moderately (R-squared = 0.68) but are largely blind to dead wood: coarse woody debris volume R-squared = 0.20 and standing dead basal area R-squared = 0.24 (Table 3). The original authors are themselves candid that airborne LiDAR cannot reliably separate late-successional from old-growth structure; our result quantifies the reason, namely that the dead-wood component central to that distinction is the attribute least predictable from canopy metrics. The authors anticipate exactly this, proposing that future work add metrics such as canopy-gap density and large downed-log density to better separate late-successional from true old-growth forest; our analysis quantifies why those additions are needed. A classification keyed on canopy height and cover therefore registers tall, continuous canopy whether it is produced by an old, structurally complex stand or by an 80- to 100-year-old fast-growing stand, a failure mode the authors note for Populus. The scale of the resulting ambiguity is illustrated by ground inventory (Section 5): roughly 12.5% of Maine forest carries substantial large-tree basal area, while only about 3.9% meets a stand-age criterion for old forest. These are different criteria and the large-tree threshold is illustrative rather than definitional, but the contrast makes the mechanism concrete: large trees are far more widespread than the full old-growth structural complex, so a canopy- or height-based classifier keys on a signal that need not coincide with a structural or age-based definition. The resulting errors run in both directions rather than as a uniform bias: in aggregate the mapped class is broader than ground-defined old forest, yet independent field truthing now underway indicates local under-classification in parts of western Maine. Either way the mapped class and a structural or age-based definition diverge, consistent with the among-method spread in Section 3, which is the property a single-map prioritization must reckon with."));
k.push(tcap("Table 3. Cross-validated R-squared for predicting ground structural attributes from the eight LiDAR canopy metrics."));
k.push(tbl([
 ["Structural attribute","CV R-squared from 8 LiDAR metrics"],
 ["Live basal area in trees >= 40 cm dbh","0.68"],
 ["Number of trees >= 40 cm dbh","0.59"],
 ["Diameter variability (CV of dbh)","0.51"],
 ["Standing dead basal area (snags)","0.24"],
 ["Coarse woody debris volume","0.20"],
],[5760,3600]));

k.push(H("5.  Ground-based inventory: the estimate, with the interval the map omits",HeadingLevel.HEADING_1));
k.push(P("Airborne LiDAR, TreeMap, and spaceborne canopy height are all proxies for the ground-based structural measurements that define LSOG. The USDA Forest Inventory and Analysis (FIA) program provides those measurements under a probability sample, which permits design-based estimates with sampling-error variance. Using rFIA design-based estimation (post-stratified, with FIA estimation-unit areas; Stanke et al. 2020) over all Maine inventory years, the area of older forest by transparent ground criteria is (2024, 95% CI): stand age >= 100 yr, 12.1% [10.9, 13.2] of forestland; stand age >= 120 yr, 3.9% [3.3, 4.6]; stand age >= 150 yr, 0.7% [0.4, 1.0]; and live basal area in trees >= 40 cm dbh exceeding 30 ft-squared/ac, 12.5% [11.4, 13.7] (Table 4). In the northern timberland units that approximate the study area, the stand age >= 120 yr estimate is 4.2% [3.3, 5.1]. FIA stand age is modeled and is less reliable in the uneven-aged Acadian stands common to the region, which is why we report the large-tree basal-area domain alongside it; the two structural and age-based criteria bracket a consistent range. The increasing trend is robust to the large-tree threshold: at 20, 30, and 40 ft-squared/ac the older-forest share is 19.5%, 12.5%, and 8.2% of forestland, each rising over 2003-2024 with confidence intervals excluding zero (Appendix S1). The point estimate for older forest brackets the published LS+OGL figure of 3.9%, which is reassuring, but the original analysis reported that figure without an interval; the ground-based gold standard places it in a range of roughly 3.3 to 4.6%, and that uncertainty is exactly what a $200-300 million prioritization should carry."));
k.push(P("The design-based series also addresses the loss premise directly. The map is motivated in part by rapid LSOG loss, reported at 1.37% per year overall and 2.19% per year on commercial timberland. That figure is a gross harvest flux: it counts mapped LSOG hectares that subsequently experienced canopy removal in the Global Forest Watch record, and it does not net out ingrowth, the younger stands that mature into older condition each year. The original authors are explicit about this asymmetry: they state they had no way in this study to estimate the amount and rate of forest growing into an LSOG condition, and they note that on federal Pacific Northwest forests older forest increased over 1993-2017 because ingrowth exceeded harvest (Hagan et al. 2026). Our design-based series supplies the side their data could not, and it moves the other way. Over 2003-2024, older forest increased by every ground measure, with confidence intervals excluding zero: stand age >= 100 yr at +0.19% of forestland per year [0.15, 0.23], stand age >= 120 yr at +0.065% per year [0.054, 0.075], and large-tree basal area at +0.17% per year [0.15, 0.18], while total forestland area was essentially flat (Fig. 2); the robust claim is the direction, not a precise rate. The increase holds where it matters most for certification and policy. On private commercial timberland specifically, older forest (stand age >= 120 yr) is 3.3% [2.7, 4.0] and rising at +0.031% per year (confidence interval excluding zero), and the large-tree basal-area share is 11.5% and rising; public land carries more older forest (10.8%) and is also increasing (Appendix S1). A stock that rises on commercial land while roughly 2% of it is harvested each year implies that ingrowth, the aging of younger stands into older condition, exceeds harvest removals: the reported loss is a gross flux, and the net flow is positive. Where a rate of loss is invoked to convey urgency, the flux and the net stock should be distinguished."));
k.push(P("Finally, the original analysis does not benchmark its map against any independent product; although it references GEDI-based structural work (de Conto et al. 2024), the publicly available spaceborne canopy-height products covering the study area (Potapov et al. 2021; Lang et al. 2023) are neither cited nor used as a cross-check. They are global, repeatable, and free, but they are also coarser and noisier than airborne LiDAR or a NAIP-derived canopy height model, with documented accuracy limitations (Moudry et al. 2024). We therefore use the canopy-height product only as one independent operationalization among several to demonstrate disagreement (Section 3), never as a reference or a better map. The unbiased reference throughout this Comment is the design-based FIA estimate, not any remote-sensing product; the cross-map comparison establishes that credible alternatives disagree, and the FIA inventory establishes the ground-based amount and its interval."));
k.push(tcap("Table 4. FIA design-based older-forest area (2024) with 95% CI, statewide and in the northern timberland units, with 2003-2024 trend."));
k.push(tbl([
 ["Domain (ground criterion)","Statewide % [95% CI]","Northern units % [95% CI]","Trend %/yr [95% CI]"],
 ["Stand age >= 100 yr","12.1 [10.9, 13.2]","12.2 [10.7, 13.7]","+0.19 [0.15, 0.23]"],
 ["Stand age >= 120 yr","3.9 [3.3, 4.6]","4.2 [3.3, 5.1]","+0.065 [0.054, 0.075]"],
 ["Stand age >= 150 yr","0.7 [0.4, 1.0]","0.6 [0.2, 1.0]","+0.000 [-0.005, 0.006]"],
 ["Large-tree BA >= 30 ft-sq/ac (>=16 in)","12.5 [11.4, 13.7]","9.8 [8.4, 11.2]","+0.17 [0.15, 0.18]"],
],[3360,2160,2160,1680]));
k.push(...fig("figs/fig_fiadb_trend.png",456,271,"Fig. 2. FIA design-based older-forest area (stand age >= 120 yr) for Maine, 2003-2024, with 95% confidence intervals. The stock rises while total forestland area is flat."));

k.push(H("6.  Implications",HeadingLevel.HEADING_1));
k.push(P("None of the above argues against mapping LSOG with LiDAR, nor against conserving older forest in Maine, which we support. Read as what it measures, tall, large-tree forest, the classification is a valuable screening tool; read as a map of old-growth-grade forest to be protected at high cost, it tends to overstate the strict resource, because the bulk of its mapped area is the transitioning class rather than late-successional or old growth, even though local errors run in both directions. The risk lies less in the map than in its use: without cross-comparison against an independent product, field verification, or assessment over time, a screening product can carry unintended consequences into acquisition and policy. It follows that a single classification, however well trained, is not a sufficient basis for parcel-level expenditures of the magnitude now contemplated. Three practices would close the gap, and each addresses something the original analysis did not do. First, benchmark the map against an unbiased design-based inventory: the FIA program provides a probability sample of the same forest, and the design-based estimate of older forest, 3.9% [3.3, 4.6], is the natural reference the map can be checked against. Second, do not rely on a single remote-sensing product; cross-compare against at least one independent map and field-verify at the parcel scale before prioritization, as the authors themselves recommend for management decisions, using their rapid field protocol (Shamgochian et al. 2025). Third, report accuracy and uncertainty for every quantity taken from the map, as a range across methods and with the sampling interval, rather than as single numbers. A fourth, related point: where a rate of loss is invoked, the harvest flux and the net stock should be distinguished, because they point in opposite directions here. These practices matter most where a map underwrites cost estimates and prioritization at the scale of the recent statewide assessment (Thompson et al. 2026), whose $200-300 million estimate is computed parcel by parcel from the mapped patches and therefore inherits the map's accuracy and uncertainty directly. The Hagan et al. map is a useful and reproducible product; our point is that its usefulness for high-stakes allocation depends on the cross-map accuracy assessment and uncertainty characterization that should now accompany it."));

k.push(H("7.  Recommendations for future research",HeadingLevel.HEADING_1));
k.push(P("Several concrete steps would put LSOG mapping in Maine on firmer footing for the decisions now riding on it. First, conduct a formal accuracy assessment of the airborne map against an independent probability sample, reporting a full confusion matrix and class-wise user and producer accuracy by owner group rather than out-of-bag accuracy alone; the FIA plot network is a ready reference. Second, add structural predictors that capture the attributes canopy metrics miss, in particular dead wood and canopy gaps (canopy-gap density, large downed-log density, and multi-return or full-waveform metrics), to separate late-successional from true old-growth forest, as the original authors propose. Third, estimate ingrowth directly, through repeat LiDAR or a NAIP and GEDI time series paired with FIA growth-removal-mortality estimation, so that loss and gain are reported as a net change rather than a one-sided flux. Fourth, propagate geolocation and co-registration error explicitly, for example with the Bayesian correction of Shannon et al. (2024), before any pixel-level overlay or parcel ranking. Fifth, move from a single map to an ensemble of credible operationalizations, reporting per-pixel agreement and an uncertainty layer so that prioritization is driven by confidence rather than by one classifier. Sixth, before acquisition, field-verify a probability sample of the prioritized parcels using the published rapid protocol (Shamgochian et al. 2025) and report the sensitivity of the result to the LSOG definition used. None of these is beyond the reach of the groups already working in this landscape, and several could be done collaboratively."));

k.push(H("Data and code availability",HeadingLevel.HEADING_1));
k.push(P("All analyses, code, and derived products supporting this Comment are archived at Zenodo (concept DOI 10.5281/zenodo.20614496). Hagan et al.'s training data and code are at Zenodo 10.5281/zenodo.19696494. FIA data are from the USDA FIA DataMart, accessed June 2026."));

k.push(H("References",HeadingLevel.HEADING_1));
["Barnett, K., G. H. Aplet, and R. T. Belote. 2023. Classifying, inventorying, and mapping mature and old-growth forests in the United States. Frontiers in Forests and Global Change 5:1070372. https://doi.org/10.3389/ffgc.2022.1070372",
 "Box, G. E. P. 1976. Science and statistics. Journal of the American Statistical Association 71:791-799.",
 "de Conto, T., J. Armston, and R. Dubayah. 2024. Characterizing the structural complexity of the Earth's forests with spaceborne lidar. Nature Communications 15:8116. https://doi.org/10.1038/s41467-024-52468-2",
 "Gray, A. N., K. Pelz, G. D. Hayward, T. Schuler, W. Salverson, M. Palmer, C. Schumacher, and C. W. Woodall. 2023. Perspectives: the wicked problem of defining and inventorying mature and old-growth forests. Forest Ecology and Management 546:121350. https://doi.org/10.1016/j.foreco.2023.121350",
 "Hagan, J. M., B. Shamgochian, M. M. L. Taylor, and J. M. Reed. 2026. Using LiDAR to quantify, map, and conserve late-successional and old-growth forest in Maine, USA. Ecosphere 17:e70670.",
 "Lang, N., W. Jetz, K. Schindler, and J. D. Wegner. 2023. A high-resolution canopy height model of the Earth. Nature Ecology & Evolution 7:1778-1789. https://doi.org/10.1038/s41559-023-02206-6",
 "Moudry, V., et al. 2024. Comparison of three global canopy height maps and their applicability to biodiversity modeling: accuracy issues revealed. Ecosphere 15:e70026.",
 "Pelz, K., G. Hayward, A. Gray, E. Berryman, C. Woodall, A. Nathanson, and N. Morgan. 2023. Quantifying old-growth forest of United States Forest Service public lands. Forest Ecology and Management 549:121437. https://doi.org/10.1016/j.foreco.2023.121437",
 "Potapov, P., et al. 2021. Mapping global forest canopy height through the fusion of GEDI and Landsat data. Remote Sensing of Environment 253:112165.",
 "Shamgochian, B., J. Hagan, M. Taylor, and M. Reed. 2025. LSOG Rapid Assessment Protocol (RAP) for Maine (v1.0). Our Climate Common Report, Georgetown, Maine.",
 "Shannon, E. S., A. O. Finley, D. J. Hayes, S. N. Noralez, A. R. Weiskittel, B. D. Cook, and C. Babcock. 2024. Quantifying and correcting geolocation error in spaceborne LiDAR forest canopy observations using high spatial accuracy data: a Bayesian model approach. Environmetrics 35:e2840. https://doi.org/10.1002/env.2840",
 "Spies, T. A. 2004. Ecological concepts and diversity of old-growth forests. Journal of Forestry 102(3):14-20.",
 "Spracklen, B., and D. V. Spracklen. 2021. Determination of structural characteristics of old-growth forest in Ukraine using spaceborne LiDAR. Remote Sensing 13(7):1233. https://doi.org/10.3390/rs13071233",
 "Stanke, H., A. O. Finley, A. S. Weed, B. F. Walters, and G. M. Domke. 2020. rFIA: an R package for estimation of forest attributes with the FIA database. Environmental Modelling & Software 127:104664.",
 "Thompson, J. R., A. Daigneault, J. Plisinski, I. Moon, and J. Norton. 2026. Pathways for protecting Maine's remaining late-successional and old-growth forests. Property and Environment Research Center."
].forEach(r=>k.push(new Paragraph({spacing:{after:120},indent:{left:360,hanging:360},children:[new TextRun({text:r,size:20})]})));

const doc=new Document({
  styles:{default:{document:{run:{font:"Times New Roman",size:22}}},
    paragraphStyles:[{id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,
      run:{size:24,bold:true,color:GREEN,font:"Times New Roman"},paragraph:{spacing:{before:160,after:70},keepNext:true}}]},
  sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1440,right:1440,bottom:1440,left:1440}}},
    footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,
      children:[new TextRun({text:"Weiskittel, Comment on Hagan et al. (2026), page ",size:16,color:GREY}),new TextRun({children:[PageNumber.CURRENT],size:16,color:GREY})]})]})},
    children:k}]});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync("Ecosphere_Comment_Hagan.docx",b);console.log("WROTE manuscript docx");});
